# Generated by Django 6.0.7 on 2026-08-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, default="", verbose_name="Опис / Додаткова інформація"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="Фото товару"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="purchase_currency",
            field=models.CharField(
                choices=[("EUR", "EUR (€)"), ("USD", "USD ($)"), ("UAH", "UAH (₴)")],
                default="EUR",
                max_length=3,
                verbose_name="Валюта закупки",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="selling_currency",
            field=models.CharField(
                choices=[("EUR", "EUR (€)"), ("USD", "USD ($)"), ("UAH", "UAH (₴)")],
                default="UAH",
                max_length=3,
                verbose_name="Валюта продажу",
            ),
        ),
    ]
