# Generated by Django 5.2.17 on 2026-08-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_product_description_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_barcode_analysis',
            field=models.JSONField(blank=True, default=dict, verbose_name='ШІ: Аналіз штрихкоду/артикулу'),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_image_analysis',
            field=models.JSONField(blank=True, default=dict, verbose_name='ШІ: Візуальний аналіз фото'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Штрихкод / QR / DataMatrix'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parsed_extra_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='Базові дані зі штрихкоду'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна продажу'),
        ),
    ]
