# Generated by Django 5.2.17 on 2026-08-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_location_id_alter_manufacturer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='release_year',
        ),
        migrations.AddField(
            model_name='product',
            name='package_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/labels/', verbose_name='Фото шильдика / коробки'),
        ),
    ]
