# Generated by Django 5.2.17 on 2026-08-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0005_remove_product_release_year_product_package_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufacturer_info",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Номенклатурна інформація виробника (Артикул / Партномер)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier_info",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Номенклатурна інформація постачальника",
            ),
        ),
    ]
